import type {
  ComponentKind,
  ComponentSource,
  ExampleModule,
  GeneratedFile,
  SkillCatalog,
  UiMethodCapability,
} from './types.ts';
import { PUBLISHED_REGION_END, PUBLISHED_REGION_START } from './types.ts';

export const SKILL_NAME = 'pi-ui-extension-ui';
export const SKILL_DIR = 'skills/pi-ui-extension-ui';
const GENERATED_BANNER =
  '<!-- GENERATED by scripts/generate-extension-ui-skill.ts from src/lib/extension-ui-capabilities — do not edit -->';
export const SKILL_DESCRIPTION =
  'Use when writing or modifying a Pi extension that calls ctx.ui (dialogs, widgets, custom components, status, header/footer, composer) and you need to know how it renders in Pi UI.';

const MENTAL_MODEL = `## Mental model

Pi UI runs your extension's pi-tui factories on the server, converts supported components into native web controls, and uses a terminal emulator only for keyboard-driven UI.`;
const CUSTOM_DIALOG = (catalog: SkillCatalog) => `## How custom() is presented

- **Rich dialog:** ${catalog.customDialog.richDialog} It refreshes every ${catalog.limits.customRefreshMs} ms.
- **Terminal fallback:** ${catalog.customDialog.terminalFallback}

Prefer the rich path by returning parsable components and wiring callbacks; use the terminal fallback only for genuinely keyboard-driven UI.`;
const RENDERING_RULES = `## Rules for good Pi UI rendering

- Prefer pi-tui components that Pi UI can parse into native controls.
- Wire component callbacks such as \`onSelect\`, \`onSubmit\`, \`onClick\`, and \`onToggle\` instead of handling raw keys where possible.
- Keep header and footer content to text; rich component structure is flattened there.
- Design for narrow and mobile widths.
- For live UI, mutate state and let the component update instead of repeatedly re-prompting.
- Stay within the documented component and wire limits.`;
const PORTABILITY = (catalog: SkillCatalog) => {
  const shapeKinds = (Object.keys(catalog.components) as ComponentKind[])
    .filter((kind) => catalog.components[kind].sources.some((source) => source.via === 'shape'))
    .map((kind) => {
      const source = catalog.components[kind].sources.find(
        (candidate) => candidate.via === 'shape'
      );
      if (source?.via !== 'shape') return '';
      const required = source.requiredFields.map((field) => `\`${field}\``).join(', ');
      const optional = source.optionalFields?.length
        ? `; optional ${source.optionalFields.map((field) => `\`${field}\``).join(', ')}`
        : '';
      return `- \`${kind}\`: required ${required}${optional}`;
    });
  return `## Portability

The same extension must also work in the terminal TUI.

${shapeKinds.join('\n')}

These shapes render natively only in Pi UI, so each needs a real \`render(width)\` for the terminal TUI.`;
};

/** One helper keeps all generated table cells safe from Markdown delimiters and line breaks. */
function mdCell(value: unknown): string {
  return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function supportSurface(support: UiMethodCapability['support']): string {
  return support.level === 'ignored' ? '—' : support.surface;
}

function methodTables(catalog: SkillCatalog): { choosing: string; atAGlance: string } {
  const rows = Object.entries(catalog.uiMethods) as [string, UiMethodCapability][];
  const decisions = rows
    .filter(([, method]) => method.useWhen || method.avoidWhen)
    .map(
      ([name, method]) =>
        `| ${mdCell(name)} | ${mdCell(method.useWhen ?? '—')} | ${mdCell(method.avoidWhen ?? '—')} |`
    );
  const choosing = ['| Method | Use when | Avoid when |', '| --- | --- | --- |', ...decisions].join(
    '\n'
  );
  const atAGlance = [
    '| Method | Support | Surface | Caveat |',
    '| --- | --- | --- | --- |',
    ...rows.map(([name, method]) => {
      const caveats: string[] = [];
      if (method.support.level === 'degraded') caveats.push(method.support.degradation);
      if (method.support.level === 'ignored') caveats.push(method.support.behavior);
      if (method.ignoredOptions?.length)
        caveats.push(`Ignores: ${method.ignoredOptions.join(', ')}`);
      return `| ${mdCell(name)} | ${mdCell(method.support.level)} | ${mdCell(supportSurface(method.support))} | ${mdCell(caveats.join(' '))} |`;
    }),
  ].join('\n');
  return { choosing, atAGlance };
}

function skillMarkdown(catalog: SkillCatalog): string {
  const { choosing, atAGlance } = methodTables(catalog);
  return `---
name: ${SKILL_NAME}
description: ${SKILL_DESCRIPTION}
---

${GENERATED_BANNER}

# Pi UI extension UI

${MENTAL_MODEL}

${CUSTOM_DIALOG(catalog)}

## Choosing a mechanism

Choose the UI method that matches the interaction and the user-visible surface:

${choosing}

${RENDERING_RULES}

${PORTABILITY(catalog)}

## Support at a glance

${atAGlance}

## Where to read more

- [UI method details](references/ui-methods.md)
- [Component sources and limits](references/components.md)
- [Executable examples](references/examples.md)
`;
}

function describeSupport(support: UiMethodCapability['support']): string {
  if (support.level === 'ignored') return `Ignored: ${support.behavior}`;
  if (support.level === 'degraded') return support.degradation;
  return '—';
}

function uiMethodsMarkdown(catalog: SkillCatalog): string {
  const rows = Object.entries(catalog.uiMethods) as [string, UiMethodCapability][];
  return `# UI methods

| Method | Level | Surface | What appears | Degradation or ignored behavior | Ignored options |
| --- | --- | --- | --- | --- | --- |
${rows
  .map(
    ([name, method]) =>
      `| ${mdCell(name)} | ${mdCell(method.support.level)} | ${mdCell(supportSurface(method.support))} | ${mdCell(method.summary)} | ${mdCell(describeSupport(method.support))} | ${mdCell(method.ignoredOptions?.join(', ') ?? '—')} |`
  )
  .join('\n')}
`;
}

function sourceDescription(source: ComponentSource): string {
  if (source.via === 'pi-tui') return `pi-tui exports: ${source.exports.join(', ')}`;
  const optional = source.optionalFields?.length
    ? `; optional: ${source.optionalFields.join(', ')}`
    : '';
  return `shape fields — required: ${source.requiredFields.join(', ')}${optional}`;
}

const CODE_FENCE = '```';
function formatLimit(value: number, unit: 'chars' | 'ms'): string {
  if (unit === 'ms') return `${value} ms`;
  return `${value.toLocaleString('en-US')} characters (${(value / 1024).toLocaleString('en-US', { maximumFractionDigits: 2 })} KB)`;
}

function componentsMarkdown(catalog: SkillCatalog): string {
  const kinds = Object.keys(catalog.components) as ComponentKind[];
  const componentRows = kinds.map((kind) => {
    const component = catalog.components[kind];
    return `| ${mdCell(kind)} | ${mdCell(component.sources.map(sourceDescription).join('; '))} | ${mdCell(component.rendersAs)} | ${mdCell(component.interaction)} | ${mdCell(component.notes?.join(' ') ?? '—')} |`;
  });
  const exports = Object.entries(catalog.piTuiExports);
  const exportRows = exports.map(
    ([name, capability]) =>
      `| ${mdCell(name)} | ${mdCell(capability.parsesAs)} | ${mdCell(capability.note)} |`
  );
  return `# Component reference

| Kind | Sources | Renders as | Interaction | Notes |
| --- | --- | --- | --- | --- |
${componentRows.join('\n')}

## Parser rules

${catalog.parserRules.map((rule) => `- ${mdCell(rule)}`).join('\n')}

## pi-tui runtime exports

| Export | Parses as | Notes |
| --- | --- | --- |
${exportRows.join('\n')}

## Theme colors

${catalog.themeColors.map(mdCell).join(', ')}

## Limits

| Limit | Value |
| --- | --- |
| Parsed component nodes | ${mdCell(catalog.limits.maxNodes)} |
| Items per parsed node | ${mdCell(catalog.limits.maxItemsPerNode)} |
| Component tree depth | ${mdCell(catalog.limits.maxDepth)} |
| Component tree text | ${mdCell(formatLimit(catalog.limits.maxTreeChars, 'chars'))} |
| Image data | ${mdCell(formatLimit(catalog.limits.maxImageChars, 'chars'))} |
| Widget refresh interval | ${mdCell(catalog.limits.widgetRefreshMs)} ms |
| Custom dialog refresh interval | ${mdCell(catalog.limits.customRefreshMs)} ms |
`;
}

function importStatements(source: string): string[] {
  const imports: string[] = [];
  const lines = source.split(/(?<=\n)/);
  for (let i = 0; i < lines.length; i++) {
    if (!/^\s*import\b/.test(lines[i])) continue;
    let statement = '';
    for (; i < lines.length; i++) {
      statement += lines[i];
      const trimmed = statement.trimEnd();
      if (/^\s*import\s*(['"])[^'"\n]+\1\s*;?\s*$/.test(trimmed)) break;
      if (/\bfrom\s*(['"])[^'"\n]+\1\s*;?\s*$/.test(trimmed)) break;
    }
    imports.push(statement.trim());
  }
  return imports;
}

export function extractPublishedRegion(source: string): string {
  const starts = source.split(PUBLISHED_REGION_START).length - 1;
  const ends = source.split(PUBLISHED_REGION_END).length - 1;
  if (starts !== 1 || ends !== 1) {
    throw new Error(
      `Expected exactly one published region (${PUBLISHED_REGION_START} and ${PUBLISHED_REGION_END}); found ${starts} start marker(s) and ${ends} end marker(s).`
    );
  }
  const start = source.indexOf(PUBLISHED_REGION_START) + PUBLISHED_REGION_START.length;
  const end = source.indexOf(PUBLISHED_REGION_END);
  if (end < start) throw new Error('Published region end marker appears before its start marker.');
  const lines = source
    .slice(start, end)
    .replace(/^\r?\n/, '')
    .replace(/\r?\n\s*$/, '')
    .split(/\r?\n/);
  const nonEmpty = lines.filter((line) => line.trim().length > 0);
  const indentation = nonEmpty.length
    ? Math.min(...nonEmpty.map((line) => line.match(/^[ \t]*/)?.[0].length ?? 0))
    : 0;
  return lines
    .map((line) => line.slice(Math.min(indentation, line.match(/^[ \t]*/)?.[0].length ?? 0)))
    .join('\n');
}

function publishedSnippet(module: ExampleModule, source: string): string {
  const imports = importStatements(source).filter(
    (line) => !/\bfrom\s*(['"])\.\.\/types\.ts\1/.test(line)
  );
  const body = extractPublishedRegion(source);
  const indentedBody = body
    .split('\n')
    .map((line) => (line ? `  ${line}` : ''))
    .join('\n');
  let wrapper: string;
  if (module.surface === 'custom') {
    wrapper = `const result = await ctx.ui.custom((tui, theme, keybindings, done) => {\n${indentedBody}\n});`;
  } else {
    const placement = module.placement ? `, { placement: '${module.placement}' }` : '';
    wrapper = `ctx.ui.setWidget('${module.id}', (tui, theme) => {\n${indentedBody}\n}${placement});`;
  }
  return [...imports, '', wrapper].join('\n');
}

function examplesMarkdown(examples: readonly { module: ExampleModule; source: string }[]): string {
  return `# Executable examples\n\n${examples
    .map(({ module, source }) => {
      const expected =
        module.expected === 'terminal-fallback' ? 'terminal fallback' : module.expected;
      return `## ${mdCell(module.title)}\n\n- Surface: ${mdCell(module.surface)}\n- Expected kind: ${mdCell(expected)}\n\n${CODE_FENCE}ts\n${publishedSnippet(module, source)}\n${CODE_FENCE}`;
    })
    .join('\n\n')}\n`;
}

export function renderSkill(input: {
  catalog: SkillCatalog;
  examples: readonly { module: ExampleModule; source: string }[];
}): GeneratedFile[] {
  return [
    { path: 'SKILL.md', content: skillMarkdown(input.catalog) },
    { path: 'references/ui-methods.md', content: uiMethodsMarkdown(input.catalog) },
    { path: 'references/components.md', content: componentsMarkdown(input.catalog) },
    { path: 'references/examples.md', content: examplesMarkdown(input.examples) },
  ];
}
